name: eplus
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - archspec=0.2.5
  - asttokens=3.0.0
  - backcall=0.2.0
  - boltons=24.0.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.1.31
  - cffi=1.17.1
  - colorama=0.4.6
  - comm=0.2.2
  - conda=25.1.1
  - conda-libmamba-solver=25.1.1
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.11.0
  - cpp-expected=1.1.0
  - debugpy=1.8.13
  - decorator=5.2.1
  - distro=1.9.0
  - executing=2.1.0
  - fmt=11.0.2
  - frozendict=2.4.6
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - importlib-metadata=8.6.1
  - importlib_metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=8.12.0
  - jedi=0.19.2
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - libarchive=3.7.7
  - libcurl=8.12.1
  - libedit=3.1.20250104
  - libev=4.33
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libiconv=1.18
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libmamba=2.0.5
  - libmambapy=2.0.5
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libsodium=1.0.20
  - libsolv=0.7.30
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libxml2=2.13.6
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - lzo=2.10
  - matplotlib-inline=0.1.7
  - menuinst=2.2.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlohmann_json=3.11.3
  - openssl=3.4.1
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0.1
  - platformdirs=4.3.6
  - pluggy=1.5.0
  - prompt-toolkit=3.0.50
  - prompt_toolkit=3.0.50
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.22
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.9.21
  - python-dateutil=2.9.0.post0
  - python_abi=3.9
  - pyzmq=26.2.1
  - readline=8.2
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - ruamel.yaml=0.18.10
  - ruamel.yaml.clib=0.2.8
  - setuptools=75.8.2
  - simdjson=3.11.6
  - six=1.17.0
  - spdlog=1.15.1
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - aiosignal==1.3.2
      - attrs==25.3.0
      - beautifulsoup4==4.8.0
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.0.1
      - cloudpickle==3.1.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - dask==2024.8.0
      - diyepw==1.2.4
      - eppy==0.5.63
      - esoreader==1.2.3
      - et-xmlfile==2.0.0
      - filelock==3.18.0
      - fonttools==4.51.0
      - frozenlist==1.5.0
      - fsspec==2024.10.0
      - future==1.0.0
      - hdbscan==0.8.40
      - idna==3.7
      - importlib-resources==6.4.0
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.5
      - locket==1.0.0
      - lxml==5.2.1
      - matplotlib==3.8.4
      - mpi4py==4.0.3
      - msgpack==1.1.0
      - munch==4.0.0
      - numpy==1.26.4
      - openpyxl==3.1.5
      - pandas==1.3.2
      - partd==1.4.2
      - patsy==1.0.1
      - pillow==10.3.0
      - protobuf==6.30.2
      - pvlib==0.8.1
      - pydot3k==1.0.17
      - pyparsing==3.1.2
      - pytz==2024.1
      - pyyaml==6.0.2
      - ray==2.44.1
      - referencing==0.36.2
      - requests==2.31.0
      - rpds-py==0.24.0
      - scikit-learn==1.5.2
      - scipy==1.11.4
      - seaborn==0.13.2
      - soupsieve==2.5
      - statsmodels==0.14.4
      - threadpoolctl==3.5.0
      - tinynumpy==1.2.1
      - toolz==1.0.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - xarray==0.19.0
      - zeppy==0.1.4
prefix: /jumbo/keller-lab/Applications/mambaforge/envs/eplus
